wandb_version: 1

Learner:
  desc: null
  value:
    _name: <fastai.learner.Learner object at 0x7ff7ededdc10>
    loss_func:
      _name: FlattenedLoss of BCEWithLogitsLoss()
      axis: -1
      flatten: true
      floatify: true
      is_2d: false
    lr: 0.001
    metrics: functools.partial(<function accuracy_multi at 0x7ff86c4723b0>, thresh=0.5)
    model_dir: models
    moms:
    - 0.95
    - 0.85
    - 0.95
    opt_func: fastai.optimizer.Adam
    path: .
    splitter: __main__.model_split
    train_bn: true
    wd: null
    wd_bn_bias: false
MixedPrecision:
  desc: null
  value: true
ParamScheduler:
  desc: null
  value: true
ProgressCallback:
  desc: null
  value: true
Recorder:
  desc: null
  value:
    add_time: true
    train_metrics: false
    valid_metrics: true
TrainEvalCallback:
  desc: null
  value: true
WandbCallback:
  desc: null
  value:
    dataset_name: null
    log: gradients
    log_dataset: false
    log_model: true
    log_preds: true
    n_preds: 36
    reorder: true
    seed: 12345
    valid_dl: null
_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.6
    start_time: 1639336930
    t:
      1:
      - 1
      - 4
      - 5
      2:
      - 1
      - 4
      - 5
      3:
      - 1
      4: 3.7.6
      5: 0.12.7
      8:
      - 1
      - 5
batch per epoch:
  desc: null
  value: 210
batch size:
  desc: null
  value: 64
dataset.tfms:
  desc: null
  value: '[Pipeline: ColReader -- {''cols'': ''fname'', ''pref'': '''', ''suff'':
    '''', ''label_delim'': None} -> partial, Pipeline: ColReader -- {''cols'': ''label'',
    ''pref'': '''', ''suff'': '''', ''label_delim'': '' ''} -> MultiCategorize --
    {''vocab'': None, ''sort'': True, ''add_na'': False} -> OneHotEncode -- {''c'':
    None}]'
device:
  desc: null
  value: cuda
dls.after_batch:
  desc: null
  value: 'Pipeline: '
dls.after_item:
  desc: null
  value: 'Pipeline: TrainTransform -> ValTransform -> ToTensor'
dls.before_batch:
  desc: null
  value: 'Pipeline: '
frozen:
  desc: null
  value: true
frozen idx:
  desc: null
  value: 1
input 1 dim 1:
  desc: null
  value: 64
input 1 dim 2:
  desc: null
  value: 10
input 1 dim 3:
  desc: null
  value: 120
input 1 dim 4:
  desc: null
  value: 120
model parameters:
  desc: null
  value: 25841395
n_inp:
  desc: null
  value: 1
